# Generated by Django 2.2.10 on 2020-03-04 16:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_channel_id', models.CharField(max_length=50)),
                ('channel_id', models.CharField(max_length=50, null=True, unique=True)),
                ('backup_key', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot_id', models.IntegerField(default=1)),
                ('username', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_key', models.CharField(max_length=30)),
                ('data_value', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger_users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref_type', models.CharField(choices=[('link', 'link'), ('ref', 'ref')], default='link', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_opened', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='opened_ref', to='messenger_users.User')),
                ('user_shared', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shared_ref', to='messenger_users.User')),
            ],
        ),
        migrations.CreateModel(
            name='ChildData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_key', models.CharField(max_length=50)),
                ('data_value', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger_users.Child')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='parent_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='messenger_users.User'),
        ),
    ]
