# Generated by Django 2.2.10 on 2020-03-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_users', '0007_auto_20200306_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='channel_id',
            field=models.CharField(default=2, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
