# Generated by Django 2.2.10 on 2020-02-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='second_code',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
