# Generated by Django 2.2.10 on 2020-02-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0002_milestone_second_code'),
        ('instances', '0002_auto_20190329_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='milestones',
            field=models.ManyToManyField(through='instances.Response', to='milestones.Milestone'),
        ),
    ]
