# Generated by Django 2.2.10 on 2020-02-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0005_postinteraction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostInteraction',
        ),
    ]
