# Generated by Django 2.2.10 on 2020-03-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0007_postinteraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='bot',
        ),
    ]
