# Generated by Django 2.2.10 on 2020-03-04 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20200304_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolegroupuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
