# Generated by Django 2.2.10 on 2020-03-04 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_assignationmessengeruser_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignationmessengeruser',
            old_name='code_id',
            new_name='code',
        ),
    ]
