# Generated by Django 2.2.10 on 2020-02-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionInstanceMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('last_register_id', models.IntegerField(default=0)),
                ('qty_register', models.IntegerField(default=0)),
                ('last_data_id', models.IntegerField()),
            ],
        ),
    ]
