# Generated by Django 2.1.7 on 2019-03-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('string', 'String'), ('date', 'Date'), ('boolean', 'Boolean')], default='string', max_length=20),
        ),
    ]
